# Generated by Django 3.2.8 on 2021-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211109_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
