# Generated by Django 3.2.8 on 2023-07-18 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211109_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
